/*
  Warnings:

  - You are about to alter the column `status` on the `CutiSementara` table. The data in that column could be lost. The data in that column will be cast from `Enum(EnumId(1))` to `Enum(EnumId(3))`.
  - The values [SEDANG_DIPROSES,DISETUJUI,DITOLAK,PROSES_SURAT] on the enum `CutiSementara_status` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterTable
ALTER TABLE `CutiSementara` MODIFY `status` ENUM('DIPROSES_OPERATOR_AKADEMIK', 'DISETUJUI_OPERATOR_AKADEMIK', 'DIPROSES_KASUBBAG_AKADEMIK', 'DISETUJUI_KASUBBAG_AKADEMIK', 'SURAT_DIPROSES', 'USULAN_DISETUJUI', 'USULAN_DITOLAK') NOT NULL DEFAULT 'DIPROSES_OPERATOR_AKADEMIK';

-- AlterTable
ALTER TABLE `StatusHistory` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `action` ENUM('DIPROSES_OPERATOR_AKADEMIK', 'DISETUJUI_OPERATOR_AKADEMIK', 'DIPROSES_KASUBBAG_AKADEMIK', 'DISETUJUI_KASUBBAG_AKADEMIK', 'SURAT_DIPROSES', 'USULAN_DISETUJUI', 'USULAN_DITOLAK') NOT NULL;

-- AlterTable
ALTER TABLE `SuratKeteranganKuliah` ADD COLUMN `status` ENUM('DIPROSES_OPERATOR_AKADEMIK', 'DISETUJUI_OPERATOR_AKADEMIK', 'DIPROSES_KASUBBAG_AKADEMIK', 'DISETUJUI_KASUBBAG_AKADEMIK', 'SURAT_DIPROSES', 'USULAN_DISETUJUI', 'USULAN_DITOLAK') NOT NULL DEFAULT 'DIPROSES_OPERATOR_AKADEMIK';
