-- AlterTable
ALTER TABLE `SuratKeteranganKuliah` MODIFY `verifikasiStatus` ENUM('DIPROSES_OPERATOR_KEMAHASISWAAN', 'DISETUJUI_OPERATOR_KEMAHASISWAAN', 'DIPROSES_KASUBBAG_KEMAHASISWAAN', 'DISETUJUI_KASUBBAG_KEMAHASISWAAN', 'SURAT_DIPROSES', 'USULAN_DISETUJUI', 'USULAN_DITOLAK') NOT NULL DEFAULT 'DIPROSES_OPERATOR_KEMAHASISWAAN';
